basePath: /api/v1
definitions:
  lissanai_com_backend_internal_domain.AuthResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/lissanai_com_backend_internal_domain.User'
    type: object
  lissanai_com_backend_internal_domain.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  lissanai_com_backend_internal_domain.ForgotPasswordRequest:
    properties:
      email:
        example: john@lissanai.com
        type: string
    required:
    - email
    type: object
  lissanai_com_backend_internal_domain.LoginRequest:
    properties:
      email:
        example: john@lissanai.com
        type: string
      password:
        example: strongpassword123
        type: string
    required:
    - email
    - password
    type: object
  lissanai_com_backend_internal_domain.MessageResponse:
    properties:
      message:
        type: string
    type: object
  lissanai_com_backend_internal_domain.PushTokenRequest:
    properties:
      platform:
        example: ios
        type: string
      token:
        example: fcm_token_123
        type: string
    required:
    - platform
    - token
    type: object
  lissanai_com_backend_internal_domain.RefreshTokenRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    required:
    - refresh_token
    type: object
  lissanai_com_backend_internal_domain.RegisterRequest:
    properties:
      email:
        example: john@lissanai.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: strongpassword123
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  lissanai_com_backend_internal_domain.ResetPasswordRequest:
    properties:
      new_password:
        example: newstrongpassword123
        minLength: 8
        type: string
      token:
        example: reset_token_123
        type: string
    required:
    - new_password
    - token
    type: object
  lissanai_com_backend_internal_domain.SocialAuthRequest:
    properties:
      access_token:
        example: ya29.a0AfH6SMC...
        type: string
      email:
        example: john@lissanai.com
        type: string
      name:
        example: John Doe
        type: string
      provider:
        example: google
        type: string
    required:
    - access_token
    - provider
    type: object
  lissanai_com_backend_internal_domain.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
    type: object
  lissanai_com_backend_internal_domain.UpdateProfileRequest:
    properties:
      name:
        example: John Updated
        type: string
      settings:
        additionalProperties: true
        type: object
    type: object
  lissanai_com_backend_internal_domain.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      settings:
        additionalProperties: true
        type: object
      updated_at:
        type: string
    type: object
  lissanai_com_backend_internal_domain_models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  lissanai_com_backend_internal_domain_models.Feedback:
    properties:
      feedback_points:
        items:
          $ref: '#/definitions/lissanai_com_backend_internal_domain_models.FeedbackPoint'
        type: array
      overall_summary:
        type: string
      score_percentage:
        type: integer
    type: object
  lissanai_com_backend_internal_domain_models.FeedbackPoint:
    properties:
      focus_phrase:
        type: string
      suggestion:
        type: string
      type:
        description: grammar, pronunciation, structure
        type: string
    type: object
  lissanai_com_backend_internal_domain_models.NextQuestionReturn:
    properties:
      question:
        type: string
    type: object
  lissanai_com_backend_internal_domain_models.SessionReturn:
    properties:
      question_number:
        type: integer
      session_id:
        type: string
    type: object
  lissanai_com_backend_internal_domain_models.SessionSummary:
    properties:
      completed:
        type: integer
      created_at:
        type: integer
      final_score:
        description: out of 100
        type: integer
      session_id:
        type: string
      strengths:
        items:
          type: string
        type: array
      total_questions:
        type: integer
      weaknesses:
        items:
          type: string
        type: array
    type: object
  lissanai_com_backend_internal_domain_models.SubmitAnswerRequest:
    properties:
      answer:
        example: My answer to the question
        type: string
      session_id:
        example: 13c70d60-8dab-4b08-b454-5225dcca1809
        type: string
    type: object
host: lissan-ai-backend-dev.onrender.com
info:
  contact: {}
  description: AI-powered English coach for Ethiopians seeking global job opportunities
  title: LissanAI Professional API
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Send password reset link to user's email
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Request password reset
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: User Login Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Login user
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Invalidate user's session token
      parameters:
      - description: Refresh Token (optional)
        in: body
        name: refreshToken
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Use refresh token to get a new access token
      parameters:
      - description: Refresh Token
        in: body
        name: refreshToken
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Refresh access token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with email and password
      parameters:
      - description: User Registration Information
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Set new password using reset token
      parameters:
      - description: Password Reset Information
        in: body
        name: resetInfo
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Reset password
      tags:
      - Auth
  /auth/social:
    post:
      consumes:
      - application/json
      description: Authenticate or register user using social providers (Google, Apple)
      parameters:
      - description: Social Authentication Information
        in: body
        name: socialInfo
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.SocialAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      summary: Social authentication
      tags:
      - Auth
  /interview/{session_id}/end:
    post:
      description: Ends the session and returns the final summary
      parameters:
      - description: Session ID
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Session summary returned
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.SessionSummary'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: End an interview session
      tags:
      - Interview
  /interview/answer:
    post:
      consumes:
      - application/json
      description: Submit an answer for the current session question
      parameters:
      - description: Answer input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain_models.SubmitAnswerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Answer submitted successfully
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.Feedback'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Submit user's answer
      tags:
      - Interview
  /interview/question:
    get:
      description: Retrieves the next question for the current session
      parameters:
      - description: Session ID
        in: query
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Next question returned
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.NextQuestionReturn'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get the next interview question
      tags:
      - Interview
  /interview/start:
    post:
      consumes:
      - application/json
      description: Creates a new interview session for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.SessionReturn'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain_models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Start a new interview session
      tags:
      - Interview
  /users/me:
    delete:
      description: Allow a user to delete their account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete user account
      tags:
      - Users
    get:
      description: Get the profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: Update parts of the user's profile (name, settings)
      parameters:
      - description: Profile Update Information
        in: body
        name: profileInfo
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user profile
      tags:
      - Users
  /users/me/push-token:
    post:
      consumes:
      - application/json
      description: Register a device token (FCM/APNs) for push notifications
      parameters:
      - description: Push Token Information
        in: body
        name: tokenInfo
        required: true
        schema:
          $ref: '#/definitions/lissanai_com_backend_internal_domain.PushTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/lissanai_com_backend_internal_domain.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Register push token
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
